version: "3.2"

services:

  twitter:
    build: .
    container_name: twitter-bot
    volumes:
      - "./build:/home/needon/twitter/"
      - "./photo:/photo"
    ports:
      - "3001:3000"
    restart: always
